#!/usr/bin/env python3
# Copyright 2017 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
# kxtz was here :p

"""Poor man's JSON parser.

This module reads the input JSON file, retrieves from it some name/value pairs
and generates a .h file to allow a C code use the definitions.

The JSON file name is required to be passed in in the command line, the nodes
this script pays attention to are included in required_keys tuple below.
"""

import json
import sys
from datetime import datetime

required_keys = ('epoch', 'major', 'minor')


def main(json_file_name):
    current_year = datetime.now().year
    h_file_text = [f'''
/*
 * Copyright {current_year} The Chromium OS Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/* This file was autogenerated by pmjp.py, do not edit. */
''']

    with open(json_file_name, 'r', encoding='utf-8') as json_file:
        json_text = []
        for line in json_file.read().splitlines():
            json_text.append(line.split('//')[0])

    j = json.loads('\n'.join(json_text))

    for key in required_keys:
        value = j.get(key, '0')
        h_file_text.append(f'#define MANIFEST_{key.upper()} {value}')

    h_file_text.append('')
    return '\n'.join(h_file_text)


if __name__ == '__main__':
    print(main(sys.argv[1]))
