#ifndef __MINIMAL_LOADER_LAUNCH_LAUNCH_H
#define __MINIMAL_LOADER_LAUNCH_LAUNCH_H

#include <stdint.h>
#include <stddef.h>

enum launch_code {
  LAUNCH_SUCCESS = 0, 

  LAUNCH_INVALID_REGION = -1,
  LAUNCH_INVALID_MAGIC = -2,
  LAUNCH_IMAGE_TOO_SMALL = -3,
  LAUNCH_IMAGE_TOO_LARGE = -4,
  LAUNCH_RO_BASE_BEFORE_REGION = -5,
  LAUNCH_RO_MAX_AFTER_REGION = -6,
  LAUNCH_RX_BASE_BEFORE_REGION = -7,
  LAUNCH_RX_MAX_AFTER_REGION = -8,
  LAUNCH_INVALID_HASH = -9,

  LAUNCH_GENERIC_FAIL = -63
};

enum launch_code launch_image(uint32_t addr, size_t max_size);

#endif /* ifndef __MINIMAL_LOADER_LAUNCH_LAUNCH_H */