#ifndef FLASH_LAYOUT_H
#define FLASH_LAYOUT_H

#define CONFIG_TOP_SIZE 0x3000

#define CONFIG_FLASH_BASE 0x40000
#define CONFIG_FLASH_SIZE 0x80000 /* 512 KiB */
#define CONFIG_FLASH_HALF (CONFIG_FLASH_SIZE >> 1)

#define CONFIG_FLASH_BANK_SIZE 0x800

#define CONFIG_RO_SIZE 0x4000
#define CONFIG_RW_SIZE (CONFIG_FLASH_HALF - CONFIG_RO_SIZE - CONFIG_TOP_SIZE)

#define CONFIG_FLASH_SLOT_A_BASE (CONFIG_FLASH_BASE)
#define CONFIG_FLASH_SLOT_B_BASE (CONFIG_FLASH_BASE + CONFIG_FLASH_HALF)

#define CONFIG_RO_A_BASE (CONFIG_FLASH_SLOT_A_BASE)
#define CONFIG_RO_B_BASE (CONFIG_FLASH_SLOT_B_BASE)

#define CONFIG_RW_A_BASE (CONFIG_RO_A_BASE + CONFIG_RO_SIZE)
#define CONFIG_RW_B_BASE (CONFIG_RO_B_BASE + CONFIG_RO_SIZE)

#endif /* FLASH_LAYOUT_H */